UPDATE auto_csv_input_info
SET UPD_PROG = 'AutoLinkageApi',
    SUP_NAME = %(SUP_NAME)s,
    INV_REG_NUM = %(INV_REG_NUM)s,
    PAGE_NAME_1 = %(PAGE_NAME_1)s,
    PAGE_URL_1 = %(PAGE_URL_1)s,
    PAGE_NAME_2 = %(PAGE_NAME_2)s,
    PAGE_URL_2 = %(PAGE_URL_2)s,
    PAGE_NAME_3 = %(PAGE_NAME_3)s,
    PAGE_URL_3 = %(PAGE_URL_3)s,
    PAGE_NAME_4 = %(PAGE_NAME_4)s,
    PAGE_URL_4 = %(PAGE_URL_4)s,
    LOGIN_ID_1 = %(LOGIN_ID_1)s,
    LOGIN_PW_1 = %(LOGIN_PW_1)s,
    ENABLED = %(ENABLED)s,
    CONNECTION_TYPE = %(CONNECTION_TYPE)s,
    UPD_DT = %(UPD_DT)s,
    UPD_TM = %(UPD_TM)s,
    UPD_USER_ID = %(USER_ID)s
WHERE id = %(id)s
    AND CRE_USER_ID = %(USER_ID)s
    AND DEL_FLAG = 0
