-- SPDX-License-Identifier: MIT
-- Copyright (c) 2026 Home Kakeibo System Contributors

UPDATE receipt_info
SET
  UPD_PROG = :UPD_PROG,
  UPD_DT = :UPD_DT,
  UPD_TM = :UPD_TM,
  INV_REG_NUM = COALESCE(:INV_REG_NUM, INV_REG_NUM),
  SUP_NAME    = COALESCE(:SUP_NAME, SUP_NAME),
  RET_DT      = COALESCE(:RET_DT, RET_DT),
  RET_TM      = COALESCE(:RET_TM, RET_TM),
  TAX_FLAG    = COALESCE(:TAX_FLAG, TAX_FLAG),
  RET_DET_CNT = COALESCE(:RET_DET_CNT, RET_DET_CNT),
  TOA_PRICE   = COALESCE(:TOA_PRICE, TOA_PRICE)
WHERE RET_ID = :RET_ID
AND DEL_FLAG = 0;