-- SPDX-License-Identifier: MIT
-- Copyright (c) 2026 Home Kakeibo System Contributors

UPDATE receipt_info
SET
  UPD_PROG = %(UPD_PROG)s,
  UPD_DT = %(UPD_DT)s,
  UPD_TM = %(UPD_TM)s,
  INV_REG_NUM = COALESCE(%(INV_REG_NUM)s, INV_REG_NUM),
  SUP_NAME    = COALESCE(%(SUP_NAME)s, SUP_NAME),
  RET_DT      = COALESCE(%(RET_DT)s, RET_DT),
  RET_TM      = COALESCE(%(RET_TM)s, RET_TM),
  TAX_FLAG    = COALESCE(%(TAX_FLAG)s, TAX_FLAG),
  RET_DET_CNT = COALESCE(%(RET_DET_CNT)s, RET_DET_CNT),
  TOA_PRICE   = COALESCE(%(TOA_PRICE)s, TOA_PRICE)
WHERE RET_ID = %(RET_ID)s
AND DEL_FLAG = 0;