SELECT ID, RET_CONT, SOURCE_KEY
FROM KAKEIBO.AUTO_INPUT_CONT
WHERE CRE_USER_ID = %(CRE_USER_ID)s
  AND CONNECTION_TYPE = %(CONNECTION_TYPE)s
  AND COALESCE(AUTO_INPUT_STATUS, '') IN ('', 'FETCHED')
  AND DEL_FLAG = 0
ORDER BY ID
