SELECT ID FROM KAKEIBO.AUTO_INPUT_CONT
WHERE CRE_USER_ID = %(CRE_USER_ID)s AND CONNECTION_TYPE = %(CONNECTION_TYPE)s
  AND DEL_FLAG = 0
  AND (
    SOURCE_KEY = %(SOURCE_KEY)s
    OR (
      (SOURCE_KEY IS NULL OR SOURCE_KEY = '')
      AND RET_DT = %(RET_DT)s
      AND RET_CONT = %(RET_CONT)s
    )
  )
LIMIT 1
