UPDATE KAKEIBO.AUTO_INPUT_CONT
SET AUTO_INPUT_STATUS = %(AUTO_INPUT_STATUS)s,
    UPD_PROG = %(UPD_PROG)s,
    UPD_DT = %(UPD_DT)s,
    UPD_TM = %(UPD_TM)s,
    UPD_USER_ID = %(UPD_USER_ID)s
WHERE ID = %(ID)s AND CRE_USER_ID = %(CRE_USER_ID)s AND DEL_FLAG = 0
