INSERT INTO USER_INFO (
  CRE_PROG, UPD_PROG, USER_ID, USER_NAME, NICKNAME,
  USER_PASSWORD, PASSWORD_HASH, PASSWORD_SALT,
  CRE_DT, CRE_TM, UPD_DT, UPD_TM,
  CRE_USER_ID, UPD_USER_ID, DEL_FLAG
) VALUES (
  %(CRE_PROG)s, %(UPD_PROG)s, %(USER_ID)s, %(USER_NAME)s, %(NICKNAME)s,
  %(USER_PASSWORD)s, %(PASSWORD_HASH)s, %(PASSWORD_SALT)s,
  %(CRE_DT)s, %(CRE_TM)s, %(UPD_DT)s, %(UPD_TM)s,
  %(CRE_USER_ID)s, %(UPD_USER_ID)s, 0
)
