UPDATE USER_INFO
SET UPD_PROG = %(UPD_PROG)s,
    RESET_TOKEN_HASH = %(RESET_TOKEN_HASH)s,
    RESET_TOKEN_SALT = %(RESET_TOKEN_SALT)s,
    RESET_TOKEN_EXPIRES_AT = %(RESET_TOKEN_EXPIRES_AT)s,
    RESET_TOKEN_USED = 0,
    UPD_DT = %(UPD_DT)s,
    UPD_TM = %(UPD_TM)s
WHERE USER_ID = %(USER_ID)s
  AND DEL_FLAG = 0
