UPDATE USER_INFO
SET UPD_PROG = %(UPD_PROG)s,
    USER_PASSWORD = %(USER_PASSWORD)s,
    PASSWORD_HASH = %(PASSWORD_HASH)s,
    PASSWORD_SALT = %(PASSWORD_SALT)s,
    RESET_TOKEN_HASH = NULL,
    RESET_TOKEN_SALT = NULL,
    RESET_TOKEN_EXPIRES_AT = NULL,
    RESET_TOKEN_USED = 1,
    UPD_DT = %(UPD_DT)s,
    UPD_TM = %(UPD_TM)s
WHERE USER_ID = %(USER_ID)s
  AND DEL_FLAG = 0
