UPDATE USER_INFO
SET UPD_PROG = %(UPD_PROG)s,
    NICKNAME = %(NICKNAME)s,
    AVATAR_IMAGE = %(AVATAR_IMAGE)s,
    UPD_DT = %(UPD_DT)s,
    UPD_TM = %(UPD_TM)s
WHERE USER_ID = %(USER_ID)s
  AND DEL_FLAG = 0
