INSERT INTO KAKEIBO.AUTO_INPUT_CONT (
    CRE_PROG, UPD_PROG, INV_REG_NUM, RET_CONT, RET_DT, RET_TM,
    AUTO_INPUT_STATUS, CONNECTION_TYPE, SOURCE_KEY,
    CRE_DT, CRE_TM, UPD_DT, UPD_TM, CRE_USER_ID, UPD_USER_ID, DEL_FLAG
) VALUES (
    'AutoInput_Amazon', 'AutoInput_Amazon', 'AMAZON',
    %(RET_CONT)s, %(RET_DT)s, '', %(AUTO_INPUT_STATUS)s, 'AMAZON', %(SOURCE_KEY)s,
    %(CRE_DT)s, %(CRE_TM)s, %(CRE_DT)s, %(CRE_TM)s, %(CRE_USER_ID)s, %(UPD_USER_ID)s, 0
)
