UPDATE AUTO_INPUT_INFO SET
    SUICA_COOKIE_JSON = %(SUICA_COOKIE_JSON)s,
    SUICA_CHALLENGE_ID = NULL,
    SUICA_CHALLENGE_EXPIRES_AT = NULL,
    SUICA_FORM_JSON = NULL,
    SUICA_FORM_ACTION = NULL,
    LAST_LOGIN_STATUS = 'AUTHENTICATED',
    LAST_LOGIN_DT = %(LAST_LOGIN_DT)s,
    LAST_LOGIN_TM = %(LAST_LOGIN_TM)s
WHERE CRE_USER_ID = %(CRE_USER_ID)s AND CONNECTION_TYPE = 'AMAZON' AND DEL_FLAG = 0
