UPDATE AUTO_INPUT_INFO SET
    SUICA_CHALLENGE_ID = %(SUICA_CHALLENGE_ID)s,
    SUICA_CHALLENGE_EXPIRES_AT = %(SUICA_CHALLENGE_EXPIRES_AT)s,
    SUICA_COOKIE_JSON = %(SUICA_COOKIE_JSON)s,
    SUICA_FORM_JSON = %(SUICA_FORM_JSON)s,
    SUICA_FORM_ACTION = %(SUICA_FORM_ACTION)s,
    LAST_LOGIN_STATUS = 'OTP_REQUIRED'
WHERE ID = %(ID)s AND CRE_USER_ID = %(CRE_USER_ID)s AND DEL_FLAG = 0
