SELECT ID, RET_CONT
FROM KAKEIBO.AUTO_INPUT_CONT
WHERE CRE_USER_ID = %(CRE_USER_ID)s
  AND CONNECTION_TYPE = %(CONNECTION_TYPE)s
  AND AUTO_INPUT_STATUS = %(AUTO_INPUT_STATUS)s
  AND DEL_FLAG = 0
ORDER BY RET_DT DESC, ID DESC
