INSERT INTO SALARY_INFO (
    CRE_PROG, UPD_PROG, SAL_DATE, SAL_NAME, SAL_CAT, SAL_SUB_CAT,
    SAL_COMMENT, SAL_AMT, CRE_DT, CRE_TM, UPD_DT, UPD_TM,
    CRE_USER_ID, UPD_USER_ID, DEL_FLAG
)
VALUES (
    %(CRE_PROG)s, %(UPD_PROG)s, %(SAL_DATE)s, %(SAL_NAME)s, %(SAL_CAT)s, %(SAL_SUB_CAT)s,
    %(SAL_COMMENT)s, %(SAL_AMT)s, %(CRE_DT)s, %(CRE_TM)s, %(UPD_DT)s, %(UPD_TM)s,
    %(CRE_USER_ID)s, %(UPD_USER_ID)s, %(DEL_FLAG)s
)
