INSERT INTO AI_USAGE_LOG (
  CRE_PROG, PROVIDER, MODEL, FEATURE, STATUS_CODE, ERROR_CODE,
  PROMPT_TOKENS, OUTPUT_TOKENS, TOTAL_TOKENS, CACHED_TOKENS, THOUGHTS_TOKENS,
  CRE_DT, CRE_TM, CRE_USER_ID, UPD_USER_ID, DEL_FLAG
) VALUES (
  %(CRE_PROG)s, %(PROVIDER)s, %(MODEL)s, %(FEATURE)s, %(STATUS_CODE)s, %(ERROR_CODE)s,
  %(PROMPT_TOKENS)s, %(OUTPUT_TOKENS)s, %(TOTAL_TOKENS)s, %(CACHED_TOKENS)s, %(THOUGHTS_TOKENS)s,
  %(CRE_DT)s, %(CRE_TM)s, %(CRE_USER_ID)s, %(UPD_USER_ID)s, 0
)
