INSERT INTO AI_RECEIPT_ANALYSIS (
  CRE_PROG, UPD_PROG, ANALYSIS_ID, INV_REG_NUM, SUP_NAME, RET_DT, RET_TM,
  TAX_FLAG, TOA_PRICE, AI_IMAGE_MIME_TYPE, AI_OUTPUT_JSON,
  EDITED_RECEIPT_JSON, STATUS, CRE_DT, CRE_TM, UPD_DT, UPD_TM, CRE_USER_ID, UPD_USER_ID, DEL_FLAG
) VALUES (
  %(CRE_PROG)s, %(UPD_PROG)s, %(ANALYSIS_ID)s, %(INV_REG_NUM)s, %(SUP_NAME)s, %(RET_DT)s, %(RET_TM)s,
  %(TAX_FLAG)s, %(TOA_PRICE)s, %(AI_IMAGE_MIME_TYPE)s, %(AI_OUTPUT_JSON)s,
  %(EDITED_RECEIPT_JSON)s, %(STATUS)s, %(CRE_DT)s, %(CRE_TM)s, %(UPD_DT)s, %(UPD_TM)s, %(CRE_USER_ID)s, %(UPD_USER_ID)s, 0
)
