SELECT
  ANALYSIS_ID AS ANALYSISID,
  RET_ID AS RECEIPTID,
  SUP_NAME AS SUPPLIERNAME,
  RET_DT AS RECEIPTDATE,
  RET_TM AS RECEIPTTIME,
  TOA_PRICE AS TOTALPRICE,
  STATUS AS STATUS,
  CRE_DT AS CREATEDDATE,
  CRE_TM AS CREATEDTIME
FROM AI_RECEIPT_ANALYSIS
WHERE DEL_FLAG = 0
  AND CRE_USER_ID = %(CRE_USER_ID)s
ORDER BY ID DESC
LIMIT 200
