SELECT
  ANALYSIS_ID AS ANALYSISID,
  RET_ID AS RECEIPTID,
  INV_REG_NUM AS INVOICEREGISTRATIONNUMBER,
  SUP_NAME AS SUPPLIERNAME,
  RET_DT AS RECEIPTDATE,
  RET_TM AS RECEIPTTIME,
  TAX_FLAG AS TAXFLAG,
  TOA_PRICE AS TOTALPRICE,
  CASE WHEN AI_IMAGE IS NULL OR AI_IMAGE = '' THEN FALSE ELSE TRUE END AS HASIMAGE,
  AI_IMAGE_MIME_TYPE AS IMAGEMIMETYPE,
  AI_OUTPUT_JSON AS AIOUTPUTJSON,
  EDITED_RECEIPT_JSON AS EDITEDRECEIPTJSON,
  STATUS AS STATUS,
  CRE_DT AS CREATEDDATE,
  CRE_TM AS CREATEDTIME
FROM AI_RECEIPT_ANALYSIS
WHERE ANALYSIS_ID = %(ANALYSIS_ID)s
  AND CRE_USER_ID = %(CRE_USER_ID)s
  AND DEL_FLAG = 0
LIMIT 1
