UPDATE AI_RECEIPT_ANALYSIS
SET UPD_PROG = %(UPD_PROG)s,
    RET_ID = %(RET_ID)s,
    INV_REG_NUM = %(INV_REG_NUM)s,
    SUP_NAME = %(SUP_NAME)s,
    RET_DT = %(RET_DT)s,
    RET_TM = %(RET_TM)s,
    TAX_FLAG = %(TAX_FLAG)s,
    TOA_PRICE = %(TOA_PRICE)s,
    EDITED_RECEIPT_JSON = %(EDITED_RECEIPT_JSON)s,
    STATUS = %(STATUS)s,
    UPD_DT = %(UPD_DT)s,
    UPD_TM = %(UPD_TM)s,
    UPD_USER_ID = %(UPD_USER_ID)s
WHERE ANALYSIS_ID = %(ANALYSIS_ID)s
  AND CRE_USER_ID = %(CRE_USER_ID)s
  AND DEL_FLAG = 0
