INSERT INTO RECEIPT_INFO_CATEGORY2 (CATEGORY1_NAME, CATEGORY2_NAME, TAX_RATE, CRE_USER_ID, UPD_USER_ID)
VALUES (%(CATEGORY1_NAME)s, %(CATEGORY2_NAME)s, %(TAX_RATE)s, %(CRE_USER_ID)s, %(UPD_USER_ID)s)
