INSERT INTO SHOPPING_PLAN (USER_ID, ITEMS_JSON, CHECKED_JSON, UPDATED_AT)
            VALUES (%(USER_ID)s, %(ITEMS_JSON)s, %(CHECKED_JSON)s, %(UPDATED_AT)s)
            ON CONFLICT (USER_ID) DO UPDATE SET ITEMS_JSON=%(ITEMS_JSON)s,
            CHECKED_JSON=%(CHECKED_JSON)s, UPDATED_AT=%(UPDATED_AT)s
