INSERT INTO RECIPE (RECIPE_ID, USER_ID, NAME, BASE_SERVINGS,
                INGREDIENTS_JSON, STEPS_JSON, VIDEO_URL, NOTES, UPDATED_AT)
                VALUES (%(RECIPE_ID)s, %(USER_ID)s, %(NAME)s, %(BASE_SERVINGS)s, %(INGREDIENTS_JSON)s,
                %(STEPS_JSON)s, %(VIDEO_URL)s, %(NOTES)s, %(UPDATED_AT)s)
