UPDATE RECIPE SET NAME=%(NAME)s, BASE_SERVINGS=%(BASE_SERVINGS)s,
                INGREDIENTS_JSON=%(INGREDIENTS_JSON)s, STEPS_JSON=%(STEPS_JSON)s, VIDEO_URL=%(VIDEO_URL)s,
                NOTES=%(NOTES)s, UPDATED_AT=%(UPDATED_AT)s
                WHERE RECIPE_ID=%(RECIPE_ID)s AND USER_ID=%(USER_ID)s
