UPDATE AUTO_INPUT_INFO
            SET LAST_LOGIN_STATUS = %(LAST_LOGIN_STATUS)s, LAST_LOGIN_DT = %(LAST_LOGIN_DT)s, LAST_LOGIN_TM = %(LAST_LOGIN_TM)s
            WHERE ID = %(ID)s AND CRE_USER_ID = %(CRE_USER_ID)s AND DEL_FLAG = 0
