SELECT DISTINCT
    RE.RET_ID,
    RE.INV_REG_NUM,
    RE.SUP_NAME,
    RE.RET_DT,
    RE.RET_TM,
    RE.TAX_FLAG,
    RE.TOA_PRICE
FROM RECEIPT_INFO RE
WHERE RE.DEL_FLAG = 0
    AND RE.CRE_USER_ID = %(CRE_USER_ID)s
