SELECT RET_ID, ITEM_NAME, CAT1, CAT2, TAX_RATE, QTY, UT, UT_PRE, TO_PRE,
       UT_TAX_EXCLUDED, TO_TAX_EXCLUDED, UT_TAX_INCLUDED, TO_TAX_INCLUDED
FROM RECEIPT_DETAIL
WHERE RET_ID = %(RET_ID)s
  AND CRE_USER_ID = %(CRE_USER_ID)s
  AND DEL_FLAG = 0;
