UPDATE INVOICE_REGISTRATION
SET UPD_PROG = %(UPD_PROG)s,
    UPD_DT = %(UPD_DT)s,
    UPD_TM = %(UPD_TM)s,
    UPD_USER_ID = %(UPD_USER_ID)s,
    SUP_NAME = COALESCE(%(SUP_NAME)s, SUP_NAME),
    TAX_FLAG = COALESCE(%(TAX_FLAG)s, TAX_FLAG)
WHERE INV_REG_NUM = %(INV_REG_NUM)s
  AND CRE_USER_ID = %(CRE_USER_ID)s
  AND DEL_FLAG = 0;
