INSERT INTO RECURRING_EXPENSE (
    CRE_PROG, UPD_PROG, RULE_NAME, DAY_OF_MONTH, ITEM_NAME,
    CAT1, CAT2, AMOUNT, TAX_FLAG, ENABLED, LAST_RUN_MONTH, MEMO,
    CRE_DT, CRE_TM, UPD_DT, UPD_TM, CRE_USER_ID, UPD_USER_ID, DEL_FLAG
) VALUES (
    %(CRE_PROG)s, %(UPD_PROG)s, %(RULE_NAME)s, %(DAY_OF_MONTH)s, %(ITEM_NAME)s,
    %(CAT1)s, %(CAT2)s, %(AMOUNT)s, %(TAX_FLAG)s, %(ENABLED)s, %(LAST_RUN_MONTH)s, %(MEMO)s,
    %(CRE_DT)s, %(CRE_TM)s, %(UPD_DT)s, %(UPD_TM)s, %(CRE_USER_ID)s, %(UPD_USER_ID)s, 0
)
