SELECT *
FROM RECURRING_EXPENSE
WHERE DEL_FLAG = 0
  AND CRE_USER_ID = %(CRE_USER_ID)s
  AND ENABLED = 1
  AND (LAST_RUN_MONTH IS NULL OR LAST_RUN_MONTH <> %(LAST_RUN_MONTH)s)
ORDER BY DAY_OF_MONTH, ID
