SELECT
    ID,
    RULE_NAME AS RULENAME,
    DAY_OF_MONTH AS DAYOFMONTH,
    ITEM_NAME AS ITEMNAME,
    CAT1 AS CATEGORY1,
    CAT2 AS CATEGORY2,
    AMOUNT AS AMOUNT,
    TAX_FLAG AS TAXFLAG,
    ENABLED AS ENABLED,
    LAST_RUN_MONTH AS LASTRUNMONTH,
    MEMO AS MEMO
FROM RECURRING_EXPENSE
WHERE DEL_FLAG = 0
  AND CRE_USER_ID = %(CRE_USER_ID)s
ORDER BY DAY_OF_MONTH, ID
