UPDATE RECURRING_EXPENSE
SET UPD_PROG = 'RecurringExpenseApi',
    DEL_FLAG = 1,
    UPD_DT = %(UPD_DT)s,
    UPD_TM = %(UPD_TM)s,
    UPD_USER_ID = %(UPD_USER_ID)s
WHERE ID = %(ID)s
  AND CRE_USER_ID = %(CRE_USER_ID)s
  AND DEL_FLAG = 0
