SELECT CRE_USER_ID, CONNECTION_TYPE
FROM KAKEIBO.AUTO_INPUT_INFO
WHERE ENABLED = 1
  AND CONNECTION_TYPE = ANY(%(CONNECTION_TYPE)s)
  AND COALESCE(LOGIN_ID_1, '') <> ''
  AND COALESCE(LOGIN_PW_1, '') <> ''
  AND DEL_FLAG = 0
ORDER BY CRE_USER_ID, CONNECTION_TYPE
