-- SPDX-License-Identifier: MIT
-- Copyright (c) 2026 Home Kakeibo System Contributors

CREATE SCHEMA IF NOT EXISTS kakeibo;
SET search_path TO kakeibo;

CREATE TABLE IF NOT EXISTS kakeibo.user_info (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    USER_ID TEXT NOT NULL UNIQUE,
    USER_NAME TEXT NOT NULL UNIQUE,
    NICKNAME TEXT,
    AVATAR_IMAGE TEXT,
    USER_PASSWORD TEXT,
    PASSWORD_HASH TEXT NOT NULL,
    PASSWORD_SALT TEXT NOT NULL,
    RESET_TOKEN_HASH TEXT,
    RESET_TOKEN_SALT TEXT,
    RESET_TOKEN_EXPIRES_AT TEXT,
    RESET_TOKEN_USED INTEGER DEFAULT 0,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kakeibo.receipt_info (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    RET_ID TEXT NOT NULL,
    INV_REG_NUM TEXT,
    SUP_NAME TEXT,
    RET_DT TEXT,
    RET_TM TEXT,
    TAX_FLAG INTEGER,
    RET_DET_CNT INTEGER,
    TOA_PRICE DOUBLE PRECISION,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kakeibo.receipt_detail (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    RET_ID TEXT NOT NULL,
    ITEM_NAME TEXT,
    CAT1 TEXT,
    CAT2 TEXT,
    TAX_RATE DOUBLE PRECISION,
    QTY DOUBLE PRECISION,
    UT TEXT,
    UT_PRE DOUBLE PRECISION,
    TO_PRE DOUBLE PRECISION,
    UT_TAX_EXCLUDED DOUBLE PRECISION,
    TO_TAX_EXCLUDED DOUBLE PRECISION,
    UT_TAX_INCLUDED DOUBLE PRECISION,
    TO_TAX_INCLUDED DOUBLE PRECISION,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS kakeibo.invoice_registration (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    INV_REG_NUM TEXT NOT NULL,
    SUP_NAME TEXT NOT NULL,
    TAX_FLAG INTEGER,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kakeibo.receipt_info_category1 (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    CATEGORY1_NAME TEXT NOT NULL,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kakeibo.receipt_info_category2 (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    CATEGORY1_NAME TEXT NOT NULL,
    CATEGORY2_NAME TEXT NOT NULL,
    TAX_RATE NUMERIC(10, 2) DEFAULT 0,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kakeibo.salary_info_category (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    SAL_CAT TEXT NOT NULL,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kakeibo.salary_info (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    SAL_DATE TEXT NOT NULL,
    SAL_NAME TEXT NOT NULL,
    SAL_CAT TEXT NOT NULL,
    SAL_SUB_CAT TEXT,
    SAL_COMMENT TEXT,
    SAL_AMT NUMERIC(100, 2) DEFAULT 0,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kakeibo.budget_info (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    CAT1 TEXT NOT NULL,
    CAT2 TEXT,
    BUT_AMT NUMERIC(100, 2) DEFAULT 0,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kakeibo.setting_table (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    BUT_ON_OFF TEXT NOT NULL,
    BUT_CAT TEXT,
    BUDGET_PERIOD TEXT,
    DAY_DARK TEXT,
    AUTO_DAY_DARK TEXT,
    SUNRISE TEXT,
    SUNSET TEXT,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kakeibo.ai_usage_log (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    PROVIDER TEXT,
    MODEL TEXT,
    FEATURE TEXT,
    STATUS_CODE INTEGER,
    ERROR_CODE TEXT,
    PROMPT_TOKENS INTEGER DEFAULT 0,
    OUTPUT_TOKENS INTEGER DEFAULT 0,
    TOTAL_TOKENS INTEGER DEFAULT 0,
    CACHED_TOKENS INTEGER DEFAULT 0,
    THOUGHTS_TOKENS INTEGER DEFAULT 0,
    CRE_DT TEXT,
    CRE_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS kakeibo.ai_receipt_analysis (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    ANALYSIS_ID TEXT NOT NULL UNIQUE,
    RET_ID TEXT,
    INV_REG_NUM TEXT,
    SUP_NAME TEXT,
    RET_DT TEXT,
    RET_TM TEXT,
    TAX_FLAG INTEGER,
    TOA_PRICE DOUBLE PRECISION,
    AI_IMAGE TEXT,
    AI_IMAGE_MIME_TYPE TEXT,
    AI_OUTPUT_JSON TEXT,
    EDITED_RECEIPT_JSON TEXT,
    STATUS TEXT,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS kakeibo.recurring_expense (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    RULE_NAME TEXT NOT NULL,
    DAY_OF_MONTH INTEGER NOT NULL,
    ITEM_NAME TEXT NOT NULL,
    CAT1 TEXT,
    CAT2 TEXT,
    AMOUNT NUMERIC(100, 2) DEFAULT 0,
    TAX_FLAG INTEGER DEFAULT 1,
    ENABLED INTEGER DEFAULT 1,
    LAST_RUN_MONTH TEXT,
    MEMO TEXT,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kakeibo.auto_csv_input_info (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    INV_REG_NUM TEXT NOT NULL,
    SUP_NAME TEXT NOT NULL,
    PAGE_NAME_1 TEXT,
    PAGE_URL_1 TEXT,
    PAGE_NAME_2 TEXT,
    PAGE_URL_2 TEXT,
    PAGE_NAME_3 TEXT,
    PAGE_URL_3 TEXT,
    PAGE_NAME_4 TEXT,
    PAGE_URL_4 TEXT,
    PAGE_NAME_5 TEXT,
    PAGE_URL_5 TEXT,
    PAGE_NAME_6 TEXT,
    PAGE_URL_6 TEXT,
    PAGE_NAME_7 TEXT,
    PAGE_URL_7 TEXT,
    PAGE_NAME_8 TEXT,
    PAGE_URL_8 TEXT,
    PAGE_NAME_9 TEXT,
    PAGE_URL_9 TEXT,
    PAGE_NAME_10 TEXT,
    PAGE_URL_10 TEXT,
    LOGIN_ID_1 TEXT,
    LOGIN_PW_1 TEXT,
    LOGIN_ID_2 TEXT,
    LOGIN_PW_2 TEXT,
    LOGIN_ID_3 TEXT,
    LOGIN_PW_3 TEXT,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kakeibo.auto_csv_input_cont (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    INV_REG_NUM TEXT NOT NULL,
    RET_CONT TEXT,
    RET_DT TEXT,
    RET_TM TEXT,
    AUTO_INPUT_STATUS TEXT,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);