-- SPDX-License-Identifier: MIT
-- Copyright (c) 2026 Home Kakeibo System Contributors

CREATE SCHEMA IF NOT EXISTS kakeibo;
SET search_path TO kakeibo;

CREATE TABLE IF NOT EXISTS user_info (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    USER_ID TEXT NOT NULL UNIQUE,
    USER_NAME TEXT NOT NULL UNIQUE,
    NICKNAME TEXT,
    AVATAR_IMAGE TEXT,
    USER_PASSWORD TEXT,
    PASSWORD_HASH TEXT NOT NULL,
    PASSWORD_SALT TEXT NOT NULL,
    RESET_TOKEN_HASH TEXT,
    RESET_TOKEN_SALT TEXT,
    RESET_TOKEN_EXPIRES_AT TEXT,
    RESET_TOKEN_USED INTEGER DEFAULT 0,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS receipt_info (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    RET_ID TEXT NOT NULL,
    INV_REG_NUM TEXT,
    SUP_NAME TEXT,
    RET_DT TEXT,
    RET_TM TEXT,
    TAX_FLAG INTEGER,
    RET_DET_CNT INTEGER,
    TOA_PRICE DOUBLE PRECISION,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS receipt_detail (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    RET_ID TEXT NOT NULL,
    ITEM_NAME TEXT,
    CAT1 TEXT,
    CAT2 TEXT,
    TAX_RATE DOUBLE PRECISION,
    QTY DOUBLE PRECISION,
    UT TEXT,
    UT_PRE DOUBLE PRECISION,
    TO_PRE DOUBLE PRECISION,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS invoice_registration (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    INV_REG_NUM TEXT NOT NULL,
    SUP_NAME TEXT NOT NULL,
    IMG TEXT,
    TAX_FLAG INTEGER,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS receipt_info_category1 (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    CATEGORY1_NAME TEXT NOT NULL,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS receipt_info_category2 (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    CATEGORY1_NAME TEXT NOT NULL,
    CATEGORY2_NAME TEXT NOT NULL,
    TAX_RATE NUMERIC(10, 2) DEFAULT 0,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS salary_info_category (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    SAL_CAT TEXT NOT NULL,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS salary_info (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    SAL_DATE TEXT NOT NULL,
    SAL_NAME TEXT NOT NULL,
    SAL_CAT TEXT NOT NULL,
    SAL_SUB_CAT TEXT,
    SAL_COMMENT TEXT,
    SAL_AMT NUMERIC(100, 2) DEFAULT 0,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS budget_info (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    CAT1 TEXT NOT NULL,
    CAT2 TEXT,
    BUT_AMT NUMERIC(100, 2) DEFAULT 0,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS setting_table (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    BUT_ON_OFF TEXT NOT NULL,
    BUT_CAT TEXT,
    BUDGET_PERIOD TEXT,
    DAY_DARK TEXT,
    AUTO_DAY_DARK TEXT,
    SUNRISE TEXT,
    SUNSET TEXT,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_usage_log (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    PROVIDER TEXT,
    MODEL TEXT,
    FEATURE TEXT,
    STATUS_CODE INTEGER,
    ERROR_CODE TEXT,
    PROMPT_TOKENS INTEGER DEFAULT 0,
    OUTPUT_TOKENS INTEGER DEFAULT 0,
    TOTAL_TOKENS INTEGER DEFAULT 0,
    CACHED_TOKENS INTEGER DEFAULT 0,
    THOUGHTS_TOKENS INTEGER DEFAULT 0,
    CRE_DT TEXT,
    CRE_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ai_usage_log ADD COLUMN IF NOT EXISTS CRE_USER_ID TEXT;
ALTER TABLE ai_usage_log ADD COLUMN IF NOT EXISTS UPD_USER_ID TEXT;
ALTER TABLE ai_usage_log ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS ai_receipt_analysis (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    ANALYSIS_ID TEXT NOT NULL UNIQUE,
    RET_ID TEXT,
    INV_REG_NUM TEXT,
    SUP_NAME TEXT,
    RET_DT TEXT,
    RET_TM TEXT,
    TAX_FLAG INTEGER,
    TOA_PRICE DOUBLE PRECISION,
    AI_IMAGE TEXT,
    AI_IMAGE_MIME_TYPE TEXT,
    AI_OUTPUT_JSON TEXT,
    EDITED_RECEIPT_JSON TEXT,
    STATUS TEXT,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ai_receipt_analysis ADD COLUMN IF NOT EXISTS CRE_USER_ID TEXT;
ALTER TABLE ai_receipt_analysis ADD COLUMN IF NOT EXISTS UPD_USER_ID TEXT;
ALTER TABLE ai_receipt_analysis ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS recurring_expense (
    id BIGSERIAL PRIMARY KEY,
    CRE_PROG TEXT,
    UPD_PROG TEXT,
    RULE_NAME TEXT NOT NULL,
    DAY_OF_MONTH INTEGER NOT NULL,
    ITEM_NAME TEXT NOT NULL,
    CAT1 TEXT,
    CAT2 TEXT,
    AMOUNT NUMERIC(100, 2) DEFAULT 0,
    TAX_FLAG INTEGER DEFAULT 1,
    ENABLED INTEGER DEFAULT 1,
    LAST_RUN_MONTH TEXT,
    MEMO TEXT,
    CRE_DT TEXT,
    CRE_TM TEXT,
    UPD_DT TEXT,
    UPD_TM TEXT,
    CRE_USER_ID TEXT,
    UPD_USER_ID TEXT,
    DEL_FLAG INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
