INSERT INTO BABY_EVENT (EVENT_ID, BABY_ID, FAMILY_ID, EVENT_TYPE,
                HAPPENED_AT, DATA_JSON, CREATED_BY, CREATED_AT)
                VALUES (%(EVENT_ID)s, %(BABY_ID)s, %(FAMILY_ID)s, %(EVENT_TYPE)s,
                %(HAPPENED_AT)s, %(DATA_JSON)s, %(CREATED_BY)s, %(CREATED_AT)s)
