SELECT * FROM BABY_EVENT WHERE BABY_ID=%(BABY_ID)s AND FAMILY_ID=%(FAMILY_ID)s
            AND (HAPPENED_AT AT TIME ZONE 'ASIA/TOKYO')::DATE = %(HAPPENED_AT)s
            ORDER BY HAPPENED_AT DESC, CREATED_AT DESC
