UPDATE BABY_EVENT SET EVENT_TYPE=%(EVENT_TYPE)s, HAPPENED_AT=%(HAPPENED_AT)s,
                DATA_JSON=%(DATA_JSON)s WHERE EVENT_ID=%(EVENT_ID)s AND BABY_ID=%(BABY_ID)s
                AND FAMILY_ID=%(FAMILY_ID)s
