INSERT INTO SETTING_TABLE (
  CRE_PROG, UPD_PROG, BUT_ON_OFF, BUT_CAT, BUDGET_PERIOD,
  DAY_DARK, AUTO_DAY_DARK, SUNRISE, SUNSET,
  CRE_DT, CRE_TM, UPD_DT, UPD_TM, CRE_USER_ID, UPD_USER_ID, DEL_FLAG
) VALUES (
  %(CRE_PROG)s, %(UPD_PROG)s, %(BUT_ON_OFF)s, %(BUT_CAT)s, %(BUDGET_PERIOD)s,
  %(DAY_DARK)s, %(AUTO_DAY_DARK)s, %(SUNRISE)s, %(SUNSET)s,
  %(CRE_DT)s, %(CRE_TM)s, %(UPD_DT)s, %(UPD_TM)s, %(CRE_USER_ID)s, %(UPD_USER_ID)s, 0
)
