SELECT
  BUT_ON_OFF AS BUDGETENABLED,
  BUT_CAT,
  BUDGET_PERIOD AS BUDGETPERIOD,
  DAY_DARK AS DARKMODE,
  AUTO_DAY_DARK AS AUTODARK,
  SUNRISE AS SUNRISE,
  SUNSET AS SUNSET
FROM SETTING_TABLE
WHERE DEL_FLAG = 0
  AND CRE_USER_ID = %(CRE_USER_ID)s
ORDER BY ID DESC
LIMIT 1
