SELECT
  COUNT(*) AS REQUESTCOUNT,
  COALESCE(SUM(PROMPT_TOKENS), 0) AS PROMPTTOKENS,
  COALESCE(SUM(OUTPUT_TOKENS), 0) AS OUTPUTTOKENS,
  COALESCE(SUM(TOTAL_TOKENS), 0) AS TOTALTOKENS,
  COALESCE(SUM(CACHED_TOKENS), 0) AS CACHEDTOKENS,
  COALESCE(SUM(THOUGHTS_TOKENS), 0) AS THOUGHTSTOKENS
FROM AI_USAGE_LOG
WHERE DEL_FLAG = 0
  AND CRE_USER_ID = %(CRE_USER_ID)s
  AND FEATURE = 'receipt_ai'
  AND CRE_DT LIKE %(CRE_DT)s
